plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pwpcb.manager'
    compileSdk 34

    defaultConfig {
        applicationId 'com.pwpcb.manager'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            debuggable true
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
